# Generated by Django 5.1.5 on 2025-04-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campania',
            name='usuario',
        ),
    ]
