# Generated by Django 5.1.5 on 2025-05-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_campania_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('medio_conocimiento', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('genero', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('nivel_estudios', models.CharField(max_length=50)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
